version: 2.1 # CircleCI syntax version
jobs: # a collection of steps
  build: # runs that are not using Workflows must have a `build` job as the entry point
    docker: # run the steps with Docker
      - image: circleci/node:10.16.3 # ...with this image as the primary container; this is where all `steps` will run
      - image: circleci/mongo:4.2.0 # and this image as the secondary service container
    steps: # a collection of executable commands 
      - checkout # special step to check out source code to working directory
      - restore_cache: # special step to restore the dependency cache 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: 
          name: cc-test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: lint
          command: npm run lint
      - run: # run tests
          name: test-and-coverage
          environment: 
            CC_TEST_REPORTER_ID: 3f28740af30153569a3c81da5948b1c12aa13760212b2f2cf59cc8c585e78871
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ];
            then
              ./cc-test-reporter before-build
            fi
            npm run coverage
            if [ "$CIRCLE_BRANCH" == "master" ];
            then
              ./cc-test-reporter after-build -p "/home/circleci/project/" -t lcov --debug --exit-code $?
            fi
      - store_artifacts:
          path: coverage/lcov-report
          prefix: coverage
